import Link from "next/link";
export default function Privacy() {
  return <main className="policy"><h1>Kebijakan Privasi Untukmu</h1><p>Versi pengembangan Fase 1–5.</p>
    <h2>Pesan privat, foto, dan lampiran</h2><p>Isi pesan privat, foto, nama berkas, jenis berkas, dan lampiran dienkripsi di perangkat dengan AES-256-GCM. Kunci hanya dibuka di memori peramban. Server menyimpan ciphertext dan kunci yang dibungkus dengan kunci turunan Argon2id. Foto dan lampiran tetap hanya tersedia bagi pemilik akun.</p>
    <h2>Pesan publik dan tautan terbatas</h2><p>Pesan publik anonim dapat dibaca layanan dan moderator, disandikan di penyimpanan dengan kunci layanan, dan ditinjau sebelum terbit. Pesan tautan terbatas dienkripsi di perangkat pemilik, tidak masuk jelajah, dan dibuka di perangkat penerima menggunakan kunci pada fragmen tautan. Kunci tersebut tidak dikirim ke API. Tautan dapat dibuat ulang atau dicabut; salinan yang telah dibaca penerima tidak dapat ditarik kembali. Pesan tautan terbatas dari versi lama dipindahkan ke enkripsi perangkat saat pemilik masuk; tautan lama perlu dibuat ulang.</p>
    <h2>Penjadwalan dan kapsul waktu</h2><p>Pesan publik terjadwal muncul setelah waktu pembukaan dan persetujuan moderator. Tautan terbatas terjadwal belum dapat diakses penerima sebelum waktunya. Kapsul privat menampilkan penanda waktu; pemilik yang memiliki kunci tetap dapat mengelola dan membaca isinya.</p>
    <h2>Metadata</h2><p>Surel, nama akun, nama tujuan, kategori, bentuk galaksi, tanggal, suasana hati, tag, ukuran unggahan, dan waktu aktivitas terlihat oleh layanan. Jangan menuliskan isi rahasia pada metadata. Doa dan empati pengunjung tanpa akun menggunakan pengenal jaringan yang di-HMAC, tanpa menyimpan alamat IP mentah. Metrik operasional hanya memakai pola rute dan jumlah permintaan; metrik produk agregat dibatasi untuk admin. Jika Sentry diaktifkan operator, laporan hanya memuat jenis kesalahan, lingkungan, dan waktu, tanpa isi pesan, kredensial, atau identitas pengguna.</p>
    <h2>Akun dan pemulihan</h2><p>Kata sandi asli diproses di perangkat. Server menyimpan hash kredensial autentikasi dan verifier kode pemulihan. Kode ditampilkan sekali. Pemulihan dengan surel dan kode yang benar mengganti kata sandi, mempertahankan kunci pesan lama, serta mencabut seluruh sesi dan kode pemulihan lama. Tanpa kata sandi maupun kode pemulihan, layanan tidak dapat membuka pesan privat.</p>
    <h2>Ekspor, sesi, dan perangkat</h2><p>Ekspor meliputi pesan, tujuan, foto, dan lampiran milik akun, disandikan dengan kata sandi ekspor yang dipilih sendiri. Cookie pembaruan sesi bersifat HttpOnly. Sesi dapat dicabut melalui pengaturan akun. PWA hanya menyimpan aset publik; respons API, akun, pesan, dan unggahan tidak disimpan di cache luring.</p>
    <h2>Penghapusan dan pengelola</h2><p>Pesan dapat dihapus melalui Kelola pesan. Kebijakan cadangan, pembersihan berkas yang tidak lagi dipakai, identitas pengelola, dan kontak pengaduan harus ditetapkan operator sebelum layanan diterbitkan untuk umum.</p><Link href="/">Kembali ke Untukmu</Link></main>;
}
