import { useState } from "react";
import { create } from "zustand";
import { api, invalidate } from "../../lib/api/client";
import { store, type Message } from "../../lib/api/store";
import * as vault from "../../lib/crypto/vault";
import { requestChallenge } from "../account/Challenge";
const useMessage = create<{item:Message|null;text:string;releaseAt:string;privacy:Message['privasi']}>(()=>({item:null,text:"",releaseAt:"",privacy:"privat"}));
export async function openMessage(id:string) {try {const item=await store.getPesan(id);const text=await store.bacaIsi(item,true);if(text===null) throw new Error("Buka kunci enkripsi terlebih dahulu.");const time=item.releaseAt?new Date(item.releaseAt):null;useMessage.setState({item,text,privacy:item.privasi,releaseAt:time?new Date(time.getTime()-time.getTimezoneOffset()*60000).toISOString().slice(0,16):""});} catch(e) {window.UM.ui.toast(e instanceof Error?e.message:"Pesan gagal dibuka.");}}
export function ManageMessage() {
  const {item,text,releaseAt,privacy}=useMessage();const [busy,setBusy]=useState(false),[status,setStatus]=useState("");
  if(!item) return null;
  const noun = "pesan";
  async function run(task:()=>Promise<unknown>) {setBusy(true);setStatus("");try{await task();}catch(e){setStatus(e instanceof Error?e.message:"Permintaan gagal.");}finally{setBusy(false);}}
  const close=()=>{useMessage.setState({item:null,text:""});setStatus("");};
  async function refresh(){await invalidate();await Promise.all([window.UM.galaksi.refresh(),window.UM.sky.refresh()]);window.UM.galaksi.bersihkanPilihan();window.UM.ui.renderSemua();close();}
  return <div className="um-screen on z-top" style={{zIndex:70}}><div className="um-wrap narrow" role="dialog" aria-modal="true" aria-labelledby="manage-title"><div className="um-head"><h1 className="um-h1" id="manage-title">Kelola {noun}</h1><button className="um-close" disabled={busy} onClick={close} aria-label="Tutup">×</button></div><div className="um-card"><label htmlFor="manage-text" className="um-label">Isi {noun}</label><textarea id="manage-text" className="um-textarea" maxLength={40000} value={text} onChange={e=>useMessage.setState({text:e.target.value})}/>
  <div className="um-field"><label className="um-label" htmlFor="manage-release">Waktu pembukaan (opsional)</label><input id="manage-release" className="um-input" type="datetime-local" value={releaseAt} onChange={e=>useMessage.setState({releaseAt:e.target.value})}/><p className="um-hint">Waktu mengikuti perangkatmu. Kosongkan untuk membuka sekarang.</p></div>
  <div className="um-field"><label className="um-label" htmlFor="manage-privacy">Privasi pesan</label><select id="manage-privacy" className="um-select" value={privacy} onChange={e=>useMessage.setState({privacy:e.target.value as Message['privasi']})}><option value="privat">Privat</option><option value="publik">Publik anonim</option><option value="unlisted">Tautan terbatas</option></select></div>
  <div className="um-btn-row"><button className="um-btn primary" disabled={busy||!text.trim()} onClick={()=>void run(async()=>{const encrypted=privacy!=="publik";await api(`/messages/${item.id}`,{method:"PATCH",body:JSON.stringify({id:item.id,constellation_ids:item.galaksiIds,visibility:privacy==="privat"?"private":privacy==="unlisted"?"unlisted":"public_anon",payload:encrypted?await vault.encryptPesan(text,privacy,item.id):undefined,public_body:encrypted?undefined:text,turnstile_token:encrypted?undefined:await requestChallenge("publish"),tags:item.tag,mood:item.mood,date_label:item.tanggal,release_at:releaseAt?new Date(releaseAt).toISOString():null,attachment_ids:item.attachmentIds})});await refresh();})}>Simpan perubahan</button><button className="um-btn danger" disabled={busy} onClick={()=>{if(confirm(`Hapus ${noun} ini secara permanen dari akun?`)) void run(async()=>{await api(`/messages/${item.id}`,{method:"DELETE"});await refresh();});}}>Hapus {noun}</button></div>
  {item.privasi==="publik"&&<p className="um-note">Perubahan akan ditinjau ulang oleh moderator. Lampiran tetap privat untuk pemilik.</p>}
  {item.privasi==="unlisted"&&<><div className="um-btn-row"><button className="um-btn" disabled={busy} onClick={()=>void run(async()=>{const shared=await vault.encryptShare((await store.bacaIsi(item,true))!,item.id);const result=await api<{token:string}>(`/messages/${item.id}/share`,{method:"POST",body:JSON.stringify({payload:shared.payload})});setStatus(`${location.origin}/bagi#${item.id}.${result.token}.${shared.key}`);})}>Buat tautan baru</button><button className="um-btn" disabled={busy} onClick={()=>void run(async()=>{await api(`/messages/${item.id}/share`,{method:"DELETE"});setStatus("Tautan dicabut.");})}>Cabut tautan</button></div><p className="um-muted">Bagikan tautan lengkap hanya kepada orang yang kamu tuju. Kunci dalam tautan membuka pesan di perangkat penerima. Tautan baru membatalkan tautan sebelumnya; perubahan pesan mencabut semua tautan.</p></>}
  {status&&<p className="um-note" role="status" style={{overflowWrap:"anywhere",userSelect:"all"}}>{status}</p>}</div></div></div>;
}
