import {test,expect} from "@playwright/test";
import {register} from "./helpers";
test("multi-tujuan → pemulihan penuh → ekspor terenkripsi",async({page})=>{
  test.setTimeout(180000);
  const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));
  const {frame,email,recovery}=await register(page,"advanced");
  await frame.locator('#um-comp [data-act=cancel]').first().click();
  const secret="Pesan tetap utuh setelah pemulihan akun.";
  await page.frames()[1].evaluate(async secret=>{const a=await window.UM.store.saveGalaksi({nama:"Keluarga",kategori:"keluarga"}),b=await window.UM.store.saveGalaksi({nama:"Sahabat",kategori:"sahabat"});await window.UM.store.simpanPesan({galaksiId:a.id,galaksiIds:[a.id,b.id],teks:secret});},secret);
  await page.frames()[1].evaluate(()=>window.UM.account.open());
  await frame.getByRole("button",{name:"Ganti kata sandi dengan kode pemulihan"}).click();
  await frame.locator('#recovery-email').fill(email);await frame.locator('#recovery-code').fill(recovery);
  const password="kata-sandi-baru-untuk-pemulihan";
  await frame.locator('#recovery-password').fill(password);await frame.locator('#recovery-repeat').fill(password);
  await frame.getByRole('button',{name:'Pulihkan dan ganti kata sandi'}).click();
  await expect(frame.getByText('Simpan kode pemulihan',{exact:true})).toBeVisible({timeout:60000});
  expect(await frame.locator('output').innerText()).not.toBe(recovery);
  await frame.getByRole('checkbox').check();await frame.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  const data=await page.frames()[1].evaluate(async()=>{const rows=await window.UM.store.listPesan();return {count:rows.length,targets:rows[0].galaksiIds.length,text:await window.UM.store.bacaIsi(rows[0])};});
  expect(data).toEqual({count:1,targets:2,text:secret});
  await page.frames()[1].evaluate(()=>window.UM.account.open());
  await frame.locator('#um-default-privacy').selectOption('unlisted');
  await expect.poll(()=>page.frames()[1].evaluate(()=>window.UM.store.defaultPrivacy())).toBe('unlisted');
  await frame.locator('#export-password').fill('kata-sandi-ekspor-yang-panjang');
  const downloaded=page.waitForEvent('download');
  await frame.getByRole('button',{name:'Unduh ekspor terenkripsi'}).click();
  const file=await downloaded;const filePath=await file.path();expect(filePath).toBeTruthy();
  await frame.locator('#export-verify').setInputFiles(filePath!);
  await expect(frame.locator('section [role=status]')).toContainText('Berkas berhasil diverifikasi: 1 pesan, 2 tujuan, 0 berkas.',{timeout:60000});
  expect(errors).toEqual([]);
});
