import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";
import { register, login } from "./helpers";

test("publikasi → moderasi → jelajah anonim → empati dan laporan", async ({ page, browser }) => {
  // Includes registration/key derivation, two browser contexts, and a real
  // 30-second prayer. Leave time for browser teardown on software WebGL hosts.
  test.setTimeout(180000);
  test.skip(process.env.UNTUKMU_BROWSER_TEST !== "1", "Uses a test-only admin fixture; never promotes a production account.");
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (message.type() === "error") errors.push(message.text() + " " + message.location().url); });
  const { frame, email, password, registrationConsoleError } = await register(page, "social");
  await frame.locator("#um-nama").fill("Untuk sahabat");
  await frame.locator("#um-comp [data-act=next]").click();
  await frame.locator("#um-comp [data-act=next]").click();
  const text = "Terima kasih sudah hadir sebagai sahabat yang baik.";
  await frame.locator("#um-isi").fill(text);
  await frame.locator("#um-comp [data-act=next]").click();
  await frame.locator('#um-comp [data-act=priv][data-id=publik]').click();
  await frame.locator("#um-comp [data-act=save]").click();
  await expect(frame.locator("#um-comp")).not.toHaveClass(/on/);
  await frame.locator('.um-dock [data-act=jelajah]').click();
  await expect(frame.locator("#um-exp")).toHaveClass(/on/);
  await expect(frame.locator("#um-exp .um-item")).toHaveCount(0);
  execFileSync(process.env.UNTUKMU_TEST_PYTHON || "python", [resolve("../backend/tests/promote_browser_admin.py"), email], { env: process.env });
  await page.goto("/admin");
  await login(page, email, password);
  await expect(frame.getByText("Peninjauan konten", { exact: true })).toBeVisible();
  await expect(frame.getByText(text, { exact: true })).toBeVisible();
  await frame.getByRole("button", { name: "Setujui", exact: true }).click();
  await expect(frame.getByText("Tidak ada pesan yang menunggu peninjauan.")).toBeVisible();
  const context = await browser.newContext();
  const visitor = await context.newPage();
  visitor.on("pageerror", error => errors.push(error.message));
  const { frame: guest } = await register(visitor, 'social-viewer', { startComposer: false });
  await guest.locator("#um-entry [data-act=skip]").click();
  await guest.locator('.um-dock [data-act=jelajah]').click();
  await expect(guest.locator("#um-exp .txt").filter({ hasText: text })).toBeVisible();
  await guest.locator('#um-exp [data-act=empati]').first().click();
  await expect(guest.locator('#um-exp [data-act=empati]').first()).toBeDisabled();
  await guest.locator('#um-exp [data-act=lapor]').first().click();
  await guest.locator("#um-report-reason").fill("Mohon diperiksa kembali konteksnya.");
  await guest.getByRole("button", { name: "Kirim laporan", exact: true }).click();
  await expect(guest.locator("#um-report-reason")).toHaveCount(0);
  await guest.locator('#um-exp [data-act=close]').click();
  await guest.locator('.um-dock [data-act=doa]').click();
  await expect(guest.locator('#um-exp')).not.toHaveClass(/on/);
  await expect(guest.locator('#um-doa [data-act=hub-trad]')).toHaveCount(7);
  await guest.locator('#um-doa [data-act=target]').first().click();
  await expect(guest.locator('#um-doa')).toHaveClass(/on/);
  await expect(guest.locator('#um-doa [data-act=trad]')).toHaveCount(7);
  await guest.locator('#um-doa [data-act=trad][data-id=umum]').click();
  await guest.locator('#um-doa [data-act=entri][data-id=hening]').click();
  await guest.locator('#um-doa [data-act=start]').click();
  await expect(guest.locator('#um-doa [data-act=again]')).toBeVisible({timeout:65000});
  await page.frames()[1].evaluate('UM.galaksi.refresh()');
  expect(await page.frames()[1].evaluate('UM.galaksi.state.daftar.reduce((n, item) => n + item.batuTotal, 0)')).toBe(1);
  await context.close();
  expect(errors.filter(error => error !== registrationConsoleError)).toEqual([]);
});
