import { expect, test } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
import { register, login } from './helpers';

test('kurator dapat mendengarkan sumber dan memasang audio tanpa menerbitkan draf', async ({ page }) => {
  test.skip(process.env.UNTUKMU_BROWSER_TEST !== '1', 'Requires an isolated admin fixture.');
  const { frame, email, password } = await register(page, 'prayer-curator');
  await frame.locator('#um-comp .um-close').click();
  execFileSync(process.env.UNTUKMU_TEST_PYTHON || 'python', [resolve('../api/tests/promote_browser_admin.py'), email], { env: process.env });
  await page.goto('/admin');
  await login(page, email, password);
  await expect(frame.getByText('Kurasi doa dan audio', { exact: true })).toBeVisible();
  await frame.locator('#prayer-catalog').selectOption('katolik/bapa-kami-katolik');
  const preview = frame.getByLabel('Pratinjau Bapa Kami / Pater Noster (Latin)');
  await preview.evaluate(async (node: HTMLAudioElement) => { node.load(); await node.play(); node.pause(); });
  expect(await preview.evaluate((node: HTMLAudioElement) => node.duration)).toBeCloseTo(28.288, 1);
  await frame.getByLabel('Judul', { exact: true }).fill('Judul draf yang sedang diperiksa');
  await frame.getByRole('button', { name: 'Gunakan rekaman ini', exact: true }).click();
  await expect(frame.getByRole('status').filter({ hasText: 'Rekaman sudah dipasang sebagai draf' })).toBeVisible();
  await expect(frame.getByLabel('Judul', { exact: true })).toHaveValue('Judul draf yang sedang diperiksa');
  await expect(frame.getByLabel('Durasi (detik)', { exact: true })).toHaveValue('29');
  await expect(frame.getByLabel('Lisensi audio', { exact: true })).toHaveValue('CC0 1.0');
  await expect(frame.locator('[name=reviewed]')).not.toBeChecked();
  const engine = page.frames()[1];
  const catalog = await engine.evaluate('UM.store.prayerCatalog()') as {id: string; entri: {id: string; reviewed: boolean; audio: boolean; detik: number}[]}[];
  const entry = catalog.find(row => row.id === 'katolik')!.entri.find(row => row.id === 'bapa-kami-katolik')!;
  expect(entry).toMatchObject({ reviewed: false, audio: true, detik: 29 });
  await frame.locator('#prayer-catalog').selectOption('buddha/metta');
  const metta = frame.getByLabel('Pratinjau Karaṇīya Mettā Sutta');
  await metta.evaluate(async (node: HTMLAudioElement) => { node.load(); await node.play(); node.pause(); });
  expect(await metta.evaluate((node: HTMLAudioElement) => node.duration)).toBeCloseTo(143.543, 0);
  await expect(frame.getByRole('button', { name: 'Gunakan rekaman ini', exact: true })).toBeDisabled();
  await frame.getByRole('checkbox', { name: /tanpa penjualan/ }).check();
  await expect(frame.getByRole('button', { name: 'Gunakan rekaman ini', exact: true })).toBeEnabled();
});
